services:
  voyager:
    container_name: ${PROJECT_NAME}
    restart: always
    build:
      dockerfile: devDockerfile
      context: .
    volumes:
      - .:/app
    expose:
      - ${APP_PORT}
    ports:
      - ${EXPOST_PORT}:${APP_PORT}