services:
  voyager:
    container_name: ${PROJECT_NAME}
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - ${APP_PORT}
    ports:
      - ${EXPOST_PORT}:${APP_PORT}