services:
  voyager:
    container_name: ${PROJECT_NAME}
    restart: always
    build:
      dockerfile: devDockerfile
      context: .
    volumes:
      - .:/app
      - ${DATABASE_BIND_PATH}:/tmp/lancedb
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}